server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cusca_main?currentSchema=auth
    username: cusca
    password: cusca123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth
  flyway:
    enabled: true
    schemas: auth
    default-schema: auth
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
