spring.application.name=auth-service
spring.config.import=optional:configserver:http://config-server:8888
spring.datasource.url=jdbc:postgresql://localhost:5432/cusca_main?currentSchema=auth
spring.datasource.username=cusca
spring.datasource.password=cusca123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=auth

# Flyway
spring.flyway.enabled=true
spring.flyway.schemas=auth
spring.flyway.default-schema=auth
spring.flyway.baseline-on-migrate=true

server.port=8081

# Eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# JWT
jwt.secret=dqvcCyzlcofwy2BqV9jgGxhJAL0uKV7gqc5g24zhqKU=
jwt.expiration=86400000
jwt.public-key-path=/app/config/public.key
jwt.private-key-path=/app/config/private.key

# Management
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
